### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by Wonovan** [CDuke/AutoUncheckout#4]
Oh my goodness... I forgot what life was like before this plugin. What are the chances of getting a 2017 version?

**Comment by CDuke** [comment]
I'll publish a version for VS 2017 this weekend.

**Comment by NiklasRaab** [comment]
Me too! 👍 Please upload a version for 2017

**Comment by CDuke** [comment]
Version for 2017 uploaded - https://marketplace.visualstudio.com/vsgallery/37ef850a-3a84-4033-b8f7-3b5b3eeffd49
